name:                haskell-says
version:             0.1.0.0
github:              "periodic/haskell-says"
license:             BSD3
author:              "Drew Haven"
maintainer:          "drew.haven@gmail.com"
copyright:           "2020 Drew Haven"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Let the Haskell logo talk to your users!
category:            Web

description:         Please see the README on GitHub at <https://github.com/periodic/haskell-says#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-says-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-says
